store/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'product', ProductModelViewSet)
router.register(r'basket', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

store/orders/urls.py
from django.urls import path

from orders.views import (CancelTemplateView, OrderCreateView, OrderDetailView,
                          OrderListView, SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('success/', SuccessTemplateView.as_view(), name='order_success'),
    path('cancel/', CancelTemplateView.as_view(), name='order_cancel'),
    path('orders/', OrderListView.as_view(), name='orders'),
    path('order_detail/<int:pk>', OrderDetailView.as_view(), name='order_detail'),

]

store/products/urls.py
from django.urls import path

from products.views import (BasketListView, ProductDetailView, ProductListView,
                            basket_add, basket_deleted, basket_down)

app_name = 'products'

urlpatterns = [
    path('catalog', ProductListView.as_view(), name='catalog'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product'),
    path('category/<int:category_id>/', ProductListView.as_view(), name='category'),
    path('basket/<int:pk>/', BasketListView.as_view(), name='basket'),
    path('basket/add/<int:product_id>', basket_add, name='basket_add'),
    path('basket/down/<int:product_id>', basket_down, name='basket_down'),
    path('basket/deleted/<int:basket_id>', basket_deleted, name='basket_deleted'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from home.views import HomeView
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token)

]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegisterView, send_email)

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('verification/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
    path('verification/send_email/<int:user_id>/', send_email, name='send_email'),
]

store/home/models.py
from django.db import models

store/home/views.py
from django.views.generic.base import TemplateView

from common.view import TitleMixin


class HomeView(TitleMixin, TemplateView):
    template_name = 'home/index.html'
    title = 'Roselissa'

store/home/templates/home/base.html
<!DOCTYPE html>
{% load static %}
<html lang="rus" dir="ltr">
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/setting_css.css' %}">

    <link rel="icon" type='img/png' href="{% static 'img/logo.png' %}">
    <title>{{ title }}</title>
</head>
<body>

<div class="container">
    <div class="header">
        <div class="header-menu okno">
            <a href="{% url 'home' %}">
                <h1>ROSELISSA</h1>
            </a>

            <div class="menu">
                <a href="{% url 'products:catalog' %}"> Католог </a>

                {% if user.is_authenticated %}
                <a href="{% url 'products:basket' user.id %}">
                    <img src="{% static 'img/icons/basket.png' %}" alt="Корзина" width="30" height="30">
                </a>
                <div class="portfile">
                    <img src="{% static 'img/icons/user.png' %}" width="20" height="20" alt="Профиль">
                    <ul class='menu-portfile'>
                        <li><a href="{% url 'users:profile' user.id %}">Профиль</a></li>
                        <li><a href="{% url 'orders:orders' %}"> Заказы </a></li>
                        <li><a href="{% url 'users:logout' %}"> Выйти </a></li>
                        {% if user.is_superuser or user.is_staff %}
                        <li><a href="{% url 'admin:index' %}"> Админ-панель </a></li>
                        {% endif %}
                    </ul>
                </div>
                {% else %}
                <a href="{% url 'users:login' %}"> Войти </a>
                <a href="{% url 'users:register' %}"> Регистрация </a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<div class="container">
    {% block content %} {% endblock %}
</div>

</body>
</html>

store/home/templates/home/index.html
{% extends 'home/base.html' %}

{% block content %}
<div class="home-page">
  <div class="home okno">
    <div class="home-content">
      <h2>Живые цветы</h2>
      <p>У нас вы сможете найти все для вашего домашнего сада.
      Живые цветы, органические добавки, горшки, кашпои  многое другое.</p>

      <a href="{% url 'products:catalog' %}" class="button"> Перейти в католог </a>
    </div>
  </div>
</div>
{% endblock %}