store/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'product', ProductModelViewSet)
router.register(r'basket', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

store/orders/urls.py
from django.urls import path

from orders.views import (CancelTemplateView, OrderCreateView, OrderDetailView,
                          OrderListView, SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('success/', SuccessTemplateView.as_view(), name='order_success'),
    path('cancel/', CancelTemplateView.as_view(), name='order_cancel'),
    path('orders/', OrderListView.as_view(), name='orders'),
    path('order_detail/<int:pk>', OrderDetailView.as_view(), name='order_detail'),

]

store/products/urls.py
from django.urls import path

from products.views import (BasketListView, ProductDetailView, ProductListView,
                            basket_add, basket_deleted, basket_down)

app_name = 'products'

urlpatterns = [
    path('catalog', ProductListView.as_view(), name='catalog'),
    path('product/<int:pk>', ProductDetailView.as_view(), name='product'),
    path('category/<int:category_id>/', ProductListView.as_view(), name='category'),
    path('basket/<int:pk>/', BasketListView.as_view(), name='basket'),
    path('basket/add/<int:product_id>', basket_add, name='basket_add'),
    path('basket/down/<int:product_id>', basket_down, name='basket_down'),
    path('basket/deleted/<int:basket_id>', basket_deleted, name='basket_deleted'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from home.views import HomeView
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token)

]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/users/urls.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import (EmailVerificationView, UserLoginView, UserProfileView,
                         UserRegisterView, send_email)

app_name = 'users'

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name='register'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/<int:pk>/', login_required(UserProfileView.as_view()), name='profile'),
    path('verification/<str:email>/<uuid:code>/', EmailVerificationView.as_view(), name='email_verification'),
    path('verification/send_email/<int:user_id>/', send_email, name='send_email'),
]

store/products/models.py
import stripe
from django.conf import settings
from django.db import models

from users.models import User

stripe.api_key = settings.STRIPE_SECRET_KEY


class ProductCategory(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class Product(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='products_image', blank=True, null=True)
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=50, decimal_places=2)
    stripe_product_price_id = models.CharField(max_length=128, blank=True, null=True)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name}'

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.stripe_product_price_id:
            stripe_product_price = self.create_stripe_product_price()
            self.stripe_product_price_id = stripe_product_price['id']
        super(Product, self).save(force_insert=False, force_update=False, using=None, update_fields=None)

    def create_stripe_product_price(self):
        stripe_product = stripe.Product.create(name=self.name)
        stripe_product_price = stripe.Price.create(
            product=stripe_product['id'],
            unit_amount=round(self.price * 100),
            currency="rub",
        )
        return stripe_product_price


class BasketQuerySet(models.QuerySet):
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)

    def stripe_products(self):
        line_items = []
        for basket in self:
            items = {
                'price': basket.product.stripe_product_price_id,
                'quantity': basket.quantity,
            }
            line_items.append(items)
        return line_items


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    object = BasketQuerySet.as_manager()

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт: {self.product.name}'

    def sum(self):
        return self.product.price * self.quantity

    @classmethod
    def create_or_update(cls, product_id, user):
        basket = Basket.object.filter(user=user, product_id=product_id)

        if not basket.exists():
            obj = Basket.object.create(user=user, product_id=product_id, quantity=1)
            return obj, True
        else:
            obj = basket.first()
            product_count = Product.objects.filter(id=product_id).first().quantity
            if obj.quantity + 1 <= product_count:
                obj.quantity += 1
                obj.save()
                return obj, False
            else:
                return False, 'Is product max quantity'

    @classmethod
    def down_quantity(cls, product_id, user):
        basket = Basket.object.filter(user=user, product_id=product_id)

        if basket.first().quantity - 1 == 0:
            basket.delete()
        else:
            basket = basket.first()
            basket.quantity -= 1
            basket.save()

    def de_json(self):
        basket_items = {
            'product_name': self.product.name,
            'quantity': self.quantity,
            'price': float(self.product.price),
            'sum': float(self.sum())
        }
        return basket_items

store/products/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import HttpResponseRedirect
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from common.view import EmailAgainSendMixin, TitleMixin
from products.models import Basket, Product, ProductCategory


class ProductListView(TitleMixin, ListView):
    template_name = 'products/products.html'
    title = 'Каталог'
    model = Product
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data()
        context['categories'] = ProductCategory.objects.all()
        return context

    def get_queryset(self):
        queryset = super(ProductListView, self).get_queryset()
        category_id = self.kwargs.get('category_id')

        return queryset.filter(category_id=category_id) if category_id else queryset


class ProductDetailView(DetailView):
    template_name = 'products/one_product.html'
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['title'] = self.object.name
        return context


class BasketListView(TitleMixin, EmailAgainSendMixin, TemplateView):
    template_name = 'products/basket.html'
    title = 'Корзина'


@login_required
def basket_add(request, product_id):
    Basket.create_or_update(product_id=product_id, user=request.user)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_down(request, product_id):
    Basket.down_quantity(product_id=product_id, user=request.user)

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required
def basket_deleted(request, basket_id):
    basket = Basket.object.get(id=basket_id)
    basket.delete()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])

store/products/templates/products/basket.html
{% include 'home/base.html' %}
{% load static %}
{% block content %}
<div class="okno">
    <div class="basket">
        {% if user.is_verified_email or user.is_superuser or user.is_staff %}
        <h2>Корзина {% if baskets %} {{ baskets.total_quantity }} товара {% else %} пуста {% endif %}</h2>
        <div class="basket-cards">
            {% for basket in baskets %}
            <div class="basket-card">
                <div class="description">
                    <div class="">
                        <img src="{{ basket.product.image.url }}" width="200" alt="">
                    </div>
                    <div class="opisanie">
                        <h3>{{ basket.product.name }}</h3>
                        <p>{{ basket.product.description }}</p>
                        <p class='price-one'>{{ basket.product.price }}p./штука</p>
                    </div>
                </div>

                <div class="basket-price">
                    <h4 style="display: flex;align-items: center;">
                        Количество:
                        <a href="{% url 'products:basket_add'  basket.product.id %}">
                            <h1>+</h1></a>
                        {{ basket.quantity }}
                        <a href="{% url 'products:basket_down'  basket.product.id %}">
                            <h1>-</h1>
                        </a>
                    </h4>
                    <h4><a href="{% url 'products:basket_deleted'  basket.id %}">удалить</a></h4>
                    <h4>{{ basket.sum }} руб.</h4>
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="basket-result">
            <h3>Итог</h3>
            <h4> {{ baskets.total_sum }} руб.</h4>
        </div>
        <a href="{% url 'orders:order_create' %}" class="button"> Оформить заказ </a>
        {% else %}
        <div class="errors">
            <h4>Почта не подтверждена!</h4>
            <h3 style="font-size:12px; margin:5px;">
                Для того чтобы оформить заказ, нужно потвердеть почту
            </h3>
            {% if not email_again_send %}
            <h3 style="font-size:14px;">
                <a href="{% url 'users:send_email' user.id %}">Повторно отправить письмо на почту</a>
            </h3>
            {% else %}
            <h3 style="font-size:14px;">
                Письмо уже у вас на почте, повторить отправку через 5мин.
            </h3>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

store/products/templates/products/one_product.html
{% include 'home/base.html' %}
{% load static %}

{% block content %}
<div class="okno">
    <div class="one-product">
        <div class="img-op">
            <img src="{{ object.image.url}}" alt="">
        </div>
        <div class="text-op" style="padding:100px;">
            <h2>{{ object.name }}</h2>
            <p class="card-text">{{ object.description }}</p>
            <h4>{{ object.price }}руб.</h4>

            <div class="button-op">


                {% if object in basket_list %}
                {% for basket in baskets %}
                {% if object == basket.product %}
                <div class="count_buttons">
                    <a href="{% url 'products:basket_add'  object.id %}" class="button_count"> + </a>
                    <h1 style="padding: 15px; margin-top: 7px;">{{basket.quantity}}</h1>
                    <a href="{% url 'products:basket_down'  object.id %}" class="button_count"> - </a>
                </div>
                {% endif %}
                {% endfor %}
                {% else %}
                <a href="{% url 'products:basket_add'  object.id %}" class="button card-button b-op"> Купить </a>
                {% endif %}


            </div>
        </div>
    </div>
</div>
{% endblock %}

store/products/templates/products/products.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
<div class="container">
    <div class="catalog okno">
        <div class="category">
            <a href="{% url 'products:catalog' %}">Все товары</a>
            {% for category in categories %}
            <a href="{% url 'products:category' category.id %}">{{ category.name }}</a>
            {% endfor %}
        </div>

        <div class="pipa">
            <div class="products">
                {% for product in object_list %}
                {% if product.quantity != 0 %}
                <div class="card">
                    <div class="card-img">
                        <img src="{{ product.image.url }}" alt="">
                    </div>
                    <div class="card-okno">
                        <h3 style="font-weight: 500;"><a href="{% url 'products:product' product.id %}">{{ product.name
                            }}</a></h3>
                        <h3 style="text-align: center;align-items: center;margin: 5px;font-size: 14px;">
                            {{ product.description|truncatechars:100 }}
                        </h3>
                        <h4>{{ product.price }} руб.</h4>
                    </div>
                    {% if product in basket_list %}
                    {% for basket in baskets %}
                    {% if product == basket.product %}
                    <div class="count_buttons">
                        <a href="{% url 'products:basket_add'  product.id %}" class="button_count"> + </a>
                        <h1 style="padding: 15px; margin-top: 7px;">{{basket.quantity}}</h1>
                        <a href="{% url 'products:basket_down'  product.id %}" class="button_count"> - </a>
                    </div>
                    {% endif %}
                    {% endfor %}
                    {% else %}
                    <a href="{% url 'products:basket_add'  product.id %}" class="button card-button b-op"> Купить </a>
                    {% endif %}
                </div>
                {% endif %}
                {% endfor %}
            </div>

            {% if is_paginated %}
            <div class="pagination">
                <ul>
                    <li>
                        <a href="{% if page_obj.has_previous %} ?page={{ page_obj.previous_page_number }}
                         {% else %} # {% endif %}">
                            Назад
                        </a>
                    </li>
                    {% for page in paginator.page_range %}
                    <li>
                        <a href="?page={{ page }}">
                            {{ page }}
                        </a>
                    </li>
                    {% endfor %}
                    <li>
                        <a href="{% if page_obj.has_next %} ?page={{ page_obj.next_page_number }}
                         {% else %} # {% endif %}">
                            Вперед
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        {% endif %}
    </div>

</div>
{% endblock %}