store/api/urls.py
from django.urls import include, path
from rest_framework import routers

from api.views import BasketModelViewSet, ProductModelViewSet

app_name = 'api'

router = routers.DefaultRouter()
router.register(r'product', ProductModelViewSet)
router.register(r'basket', BasketModelViewSet)

urlpatterns = [
    path('', include(router.urls)),
]

store/orders/urls.py
from django.urls import path

from orders.views import (CancelTemplateView, OrderCreateView, OrderDetailView,
                          OrderListView, SuccessTemplateView)

app_name = 'orders'

urlpatterns = [
    path('create/', OrderCreateView.as_view(), name='order_create'),
    path('success/', SuccessTemplateView.as_view(), name='order_success'),
    path('cancel/', CancelTemplateView.as_view(), name='order_cancel'),
    path('orders/', OrderListView.as_view(), name='orders'),
    path('order_detail/<int:pk>', OrderDetailView.as_view(), name='order_detail'),

]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

from home.views import HomeView
from orders.views import stripe_webhook_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('accounts/', include('allauth.urls')),
    path('webhook/stripe/', stripe_webhook_view, name='stripe_webhook'),
    path('api/', include('api.urls', namespace='api')),
    path('api-token-auth/', views.obtain_auth_token)

]

if settings.DEBUG:
    urlpatterns.append(path("__debug__/", include("debug_toolbar.urls")))
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

store/orders/models.py
from django.db import models

from products.models import Basket, Product
from users.models import User


class Order(models.Model):
    CREATED = 0
    PAID = 1
    ON_WAY = 2
    DELIVERED = 3

    STATUSES = (
        (CREATED, 'Создан'),
        (PAID, 'Оплачен'),
        (ON_WAY, 'В пути'),
        (DELIVERED, 'Доставлен'),
    )

    initiator = models.ForeignKey(to=User, on_delete=models.CASCADE)
    address = models.TextField(max_length=300)
    date_create = models.DateTimeField(auto_now=True)
    status = models.PositiveSmallIntegerField(default=CREATED, choices=STATUSES)
    basket_history = models.JSONField(default=dict)

    def __str__(self):
        return f'Заказ #{self.id}. {self.initiator}'

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def order_update_after_payment(self):
        baskets = Basket.object.filter(user=self.initiator)
        self.change_count(baskets)
        self.status = self.PAID
        self.basket_history = {
            'purchased_items': [basket.de_json() for basket in baskets],
            'total_sum': float(baskets.total_sum())
        }
        baskets.delete()
        self.save()

    @staticmethod
    def change_count(basket):
        for product_in_basket in basket:
            count = product_in_basket.quantity
            product = Product.objects.get(id=product_in_basket.product.id)
            product.quantity -= count
            product.save()

store/orders/forms.py
from django import forms

from orders.models import Order


class OrderForm(forms.ModelForm):
    # address = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-title', 'style': "width: 100%;"}))

    class Meta:
        model = Order
        fields = ('address',)

store/orders/views.py
from http import HTTPStatus

import stripe
from django.conf import settings
from django.shortcuts import HttpResponse, HttpResponseRedirect, reverse
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from common.view import TitleMixin
from orders.forms import OrderForm
from orders.models import Order
from products.models import Basket

stripe.api_key = settings.STRIPE_SECRET_KEY


class OrderCreateView(TitleMixin, CreateView):
    title = 'Оформление заказа'
    template_name = 'orders/order-create.html'
    form_class = OrderForm
    model = Order
    success_url = reverse_lazy('orders:order_success')

    def post(self, request, *args, **kwargs):
        super(OrderCreateView, self).post(request, *args, **kwargs)
        baskets = Basket.object.filter(user=self.request.user)
        checkout_session = stripe.checkout.Session.create(
            line_items=baskets.stripe_products(),
            metadata={'order_id': self.object.id},
            mode='payment',
            success_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_success')),
            cancel_url='{}{}'.format(settings.DOMAIN_NAME, reverse('orders:order_cancel')),
        )

        return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)

    def form_valid(self, form):
        form.instance.initiator = self.request.user
        return super(OrderCreateView, self).form_valid(form)


@csrf_exempt
def stripe_webhook_view(request):
    payload = request.body
    sig_header = request.META['HTTP_STRIPE_SIGNATURE']
    event = None

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, settings.STRIPE_WEBHOOK_SECRET
        )
    except ValueError as e:
        return HttpResponse(status=400)
    except stripe.error.SignatureVerificationError as e:
        return HttpResponse(status=400)

    # Handle the checkout.session.completed event
    if event['type'] == 'checkout.session.completed':
        session = stripe.checkout.Session.retrieve(
            event['data']['object']['id'],
            expand=['line_items'],
        )

        line_items = session
        # Fulfill the purchase...
        fulfill_order(line_items)

    return HttpResponse(status=200)


def fulfill_order(session):
    order_id = int(session.metadata.order_id)
    order = Order.objects.get(id=order_id)
    order.order_update_after_payment()


class OrderListView(TitleMixin, ListView):
    template_name = 'orders/orders.html'
    title = 'Заказы'
    queryset = Order.objects.all()
    ordering = ('-date_create',)

    def get_queryset(self):
        queryset = super(OrderListView, self).get_queryset()
        return queryset.filter(initiator=self.request.user)


class OrderDetailView(DetailView):
    template_name = 'orders/order.html'
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderDetailView, self).get_context_data(**kwargs)
        context['title'] = f'#{self.object.id}'
        return context


class SuccessTemplateView(TitleMixin, TemplateView):
    title = 'Успех!'
    template_name = 'orders/success.html'


class CancelTemplateView(TitleMixin, TemplateView):
    title = 'Успех!'
    template_name = 'orders/cancel.html'

store/orders/templates/orders/cancel.html
{% include 'home/base.html' %}

{% block content %}
<div class="okno">
    <div class="order-basket">
        <h2>Ваш заказ отменен...</h2>
        <a href="{% url 'home' %}" class="button" style="margin: 50px;"> На главную страницу...</a>
    </div>
</div>
{% endblock %}

store/orders/templates/orders/order-create.html
{% include 'home/base.html' %}
{% load static %}
{% block content %}
<div class="okno">
    <div class="order-basket">
        <h2>Оформление заказа</h2>

        <div class="order-basket-cards">
            {% for basket in baskets %}
            <div class="basket-card">
                <div class="description">
                    <div class="">
                        <img src="{{ basket.product.image.url }}" width="80">
                    </div>
                    <div class="opisanie">
                        <h3>{{ basket.product.name }}</h3>
                        <p class='price-one'>{{ basket.product.price }}p./штука</p>
                    </div>
                </div>

                <div class="basket-price">
                    <h4>Количество: {{basket.quantity }}</h4>
                    <h4>{{ basket.sum }} руб.</h4>
                </div>
            </div>
            {% endfor %}
        </div>

        <div class="basket-result" style="width: 80%;">
            <h3>Итог</h3>
            <h4> {{ baskets.total_sum }} руб.</h4>
        </div>

        <form action="{% url 'orders:order_create' %}" method="post" style="width: 80%;">
            {% csrf_token %}
            <div class="form-input">
                <label for="address"> Адрес </label>
                <input type="text" name="address"  class="form-title" style="width: 100%;">
            </div>
            <button type="submit" name="button" class="button">Оплатить</button>
        </form>


    </div>

</div>
{% endblock %}

store/orders/templates/orders/order.html
{% include 'home/base.html' %}

{% block content %}
<div class="okno">
    <div class="orders order-decor">
        <h1>Заказ #{{ object.id }}</h1>
        <table class="table">
            <thead>

            <tr class="table-light">
                <th scope="col">Название</th>
                <th scope="col">Кол-во</th>
                <th scope="col">Цена</th>
                <th scope="col">Сумма</th>
            </tr>
            </thead>
            <tbody>

            {% for purchased_item in object.basket_history.purchased_items %}
            <tr>
                <th scope="row">
                    {{ purchased_item.product_name }}
                </th>
                <td>{{ purchased_item.quantity }}</td>
                <td>{{ purchased_item.price }} руб.</td>
                <td>{{ purchased_item.sum }} руб.</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
        <p class="order-sum">Итого {{ order.basket_history.total_sum }} руб.</p>
        <a href="{% url 'orders:orders' %}">Назад</a>
    </div>
</div>
{% endblock %}

store/orders/templates/orders/orders.html
{% include 'home/base.html' %}

{% block content %}
<div class="okno">
    <div class="orders">
        <table class="table">
            <thead>
            <tr class="table-light">
                <th scope="col">#</th>
                <th scope="col">Статус</th>
                <th scope="col">Создан</th>
                <th scope="col">Итого</th>
                <th scope="col">Действие</th>
            </tr>
            </thead>
            <tbody>
            {% for order in object_list %}
            <tr>
                <th scope="row">{{ order.id }}</th>
                <td>{{ order.get_status_display }}</td>
                <td>{{ order.date_create }}</td>
                <td>{{ order.basket_history.total_sum}}руб.</td>
                <td>
                    <a href="{% url 'orders:order_detail' order.id %}">просмотреть</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
</div>
{% endblock %}

store/orders/templates/orders/success.html
{% include 'home/base.html' %}

{% block content %}
<div class="okno">
    <div class="order-basket">
        <h2>Ваш заказ успешно оформлен!</h2>
        <a href="{% url 'home' %}" class="button" style="margin: 50px;"> На главную страницу...</a>
    </div>
</div>
{% endblock %}